name: Sync Mesa Repo

on:
  workflow_dispatch:
  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Mesa repo
        run: |
          git clone --depth=1 https://gitlab.freedesktop.org/Pipetto-crypto/mesa.git mesa-src

      - name: Replace repo contents
        shell: bash
        run: |
          echo "🧹 Cleaning current repo..."
          #rm -rf ./* ./.??* || true

          echo "📦 Copying Mesa files..."
          ls mesa-src
           

          echo "🗑️ Removing temp folder..."
          #rm -rf mesa-src

      - name: Commit changes
        run: |
          cd mesa-src
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "🔄 Sync Mesa repo" || echo "No changes to commit"

      - name: Force push (overwrite repo)
        run: |
          git push origin main --force
